// Sync compiled ABIs from Hardhat artifacts into apps/web so the frontend
// always has the latest typed contract surface. Re-run after any
// `pnpm compile` that changes a contract:
//
//   pnpm --filter @g3mx/contracts sync:abi
//
// The output file is committed (so a fresh checkout can `pnpm dev` without
// needing the Hardhat toolchain) but is overwritten on every sync.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const CONTRACTS_ROOT = resolve(HERE, "..");
const WEB_CONTRACTS_DIR = resolve(
  CONTRACTS_ROOT,
  "../../apps/web/lib/contracts",
);

const SYNC_TARGETS = [
  {
    artifact: "artifacts/contracts/G3MXVault.sol/G3MXVault.json",
    out: "G3MXVault.abi.ts",
    constName: "G3MX_VAULT_ABI",
  },
];

function syncOne({ artifact, out, constName }) {
  const artifactPath = resolve(CONTRACTS_ROOT, artifact);
  if (!existsSync(artifactPath)) {
    throw new Error(
      `Artifact missing: ${artifactPath}\nRun \`pnpm compile\` first.`,
    );
  }

  const { abi } = JSON.parse(readFileSync(artifactPath, "utf-8"));
  const banner =
    "// AUTO-GENERATED by packages/contracts/scripts/sync-abi.mjs — DO NOT EDIT.\n" +
    "// Re-run `pnpm --filter @g3mx/contracts sync:abi` after recompiling.\n\n";
  const body = `export const ${constName} = ${JSON.stringify(abi, null, 2)} as const;\n`;

  mkdirSync(WEB_CONTRACTS_DIR, { recursive: true });
  const outPath = resolve(WEB_CONTRACTS_DIR, out);
  writeFileSync(outPath, banner + body);
  console.log(`✓ ${artifact}\n  → ${outPath}`);
}

for (const target of SYNC_TARGETS) {
  syncOne(target);
}
